stages:
  - prepare
  - verify
  - gapanalysis

# make sure the rules adhere to our quality guidelines
yamllint-quality:
  image: python:2.7
  stage: verify 
  before_script:
    - pip install yamllint
  script:
    - yamllint .
  rules:
    - if: $CI_COMMIT_TAG
      when: never 
    - when: always

rulecheck-quality:
  stage: verify 
  image: ruby:3-alpine
  before_script:
    - apk add --no-cache yaml-dev alpine-sdk bash
    - gem install psych yaml fileutils json-schema word_wrap
  script:
    - ./ci/schema.rb .
    - ./ci/format.rb
    - ./ci/license_header.sh
  rules:
    - if: $CI_COMMIT_TAG
      when: never 
    - when: always

mapping-check:
  stage: verify 
  image: ruby:3-alpine
  before_script:
    - apk add --no-cache yaml-dev alpine-sdk
    - gem install yaml
  script:
    - ./ci/mappings.rb
  rules:
    - if: $CI_COMMIT_TAG
      when: never 
    - when: always

# make sure that every rule has an associated test-case
rulecheck-availability:
  stage: verify 
  image: ruby:3-alpine
  before_script:
    - apk add --no-cache yaml-dev alpine-sdk
    - gem install psych yaml fileutils word_wrap
  script:
    - ./ci/availability.rb
  rules:
    - if: $CI_COMMIT_TAG
      when: never 
    - when: always

assemble:
  image: ruby:3-alpine
  stage: prepare
  before_script:
    - apk add --no-cache yaml-dev alpine-sdk bash
    - gem install psych yaml fileutils word_wrap
  script:
    - ./ci/join.rb
  artifacts:
    paths:
      - "combined.yml"
  rules:
    - when: always

semgrep-check:
  image: python:3
  stage: verify 
  needs:
    - job: assemble
      artifacts: true
  before_script:
    - pip install semgrep
  script:
    - ci/semgrep_validity_check.sh
  rules:
    - when: always

# Ensure all rule-ids are unique
unique-rule-id:
  stage: verify
  image: ruby:3-alpine
  before_script:
    - gem install yaml
  script:
    - ci/unique_ids.rb
  rules:
    - if: $CI_COMMIT_TAG
      when: never 
    - when: always

gapanalysis:
  stage: gapanalysis
  variables:
    UPSTREAM_BRANCH: $CI_COMMIT_REF_NAME
  trigger:
    project: gitlab-org/security-products/sast-rule-testing-framework/rule-testing
  rules:
    - if: $CI_COMMIT_TAG
      when: never 
    - when: always
  resource_group: "sast-rules-$CI_COMMIT_REF_SLUG"
 
